#ifndef _TERMINAL_CONSTANTS_INCLUDED_H_
#define _TERMINAL_CONSTANTS_INCLUDED_H_

/* CURSOR POSITIONING */

enum CURSOR_POSITION {
    CURSOR_POSITION_UP = 65,
    CURSOR_POSITION_DOWN = 66,
    CURSOR_POSITION_FORWARD = 67,
    CURSOR_POSITION_BACKWARD = 68,
    CURSOR_POSITION_NEXT_LINE = 69,
    CURSOR_POSITION_PREV_LINE = 70,
    CURSOR_POSITION_HORIZONTAL = 71,
    CURSOR_POSITION_VERTICAL = 100
};

/* CURSOR VISIBILITY */

enum CURSOR_BLINKING {
    CURSOR_BLINKING_ENABLE = 104,
    CURSOR_BLINKING_DISABLE = 108
};

enum CURSOR_VISIBILITY {
    CURSOR_VISIBILITY_SHOW = 104,
    CURSOR_VISIBILITY_HIDE = 108
};

/* TEXT FORMATTING */

enum SGR_FORMAT {
    SGR_DEFAULT = 0,
    SGR_BOLD = 1,
    SGR_NO_BOLD = 22,
    SGR_UNDERLINE = 4,
    SGR_NO_UNDERLINE = 24,
    SGR_NEGATIVE = 7,
    SGR_POSITIVE = 27,
    SGR_FGROUND_BLACK = 30,
    SGR_FGROUND_RED = 31,
    SGR_FGROUND_GREEN = 32,
    SGR_FGROUND_YELLOW = 33,
    SGR_FGROUND_BLUE = 34,
    SGR_FGROUND_MAGENTA = 35,
    SGR_FGROUND_CYAN = 36,
    SGR_FGROUND_WHITE = 37,
    SGR_FGROUND_EXTENDED = 38,
    SGR_FGROUND_DEFAULT = 39,
    SGR_BGROUND_BLACK = 40,
    SGR_BGROUND_RED = 41,
    SGR_BGROUND_GREEN = 42,
    SGR_BGROUND_YELLOW = 43,
    SGR_BGROUND_BLUE = 44,
    SGR_BGROUND_MAGENTA = 45,
    SGR_BGROUND_CYAN = 46,
    SGR_BGROUND_WHITE = 47,
    SGR_BGROUND_EXTENDED = 48,
    SGR_BGROUND_DEFAULT = 49,
    SGR_BRIGHT_FGROUND_BLACK = 90,
    SGR_BRIGHT_FGROUND_RED = 91,
    SGR_BRIGHT_FGROUND_GREEN = 92,
    SGR_BRIGHT_FGROUND_YELLOW = 93,
    SGR_BRIGHT_FGROUND_BLUE = 94,
    SGR_BRIGHT_FGROUND_MAGENTA = 95,
    SGR_BRIGHT_FGROUND_CYAN = 96,
    SGR_BRIGHT_FGROUND_WHITE = 97,
    SGR_BRIGHT_BGROUND_BLACK = 100,
    SGR_BRIGHT_BGROUND_RED = 101,
    SGR_BRIGHT_BGROUND_GREEN = 102,
    SGR_BRIGHT_BGROUND_YELLOW = 103,
    SGR_BRIGHT_BGROUND_BLUE = 104,
    SGR_BRIGHT_BGROUND_MAGENTA = 105,
    SGR_BRIGHT_BGROUND_CYAN = 106,
    SGR_BRIGHT_BGROUND_WHITE = 107
};

/* DEC LINE DRAWING */

enum DEC_CHARACTER_SET {
    DEC_BOTTOM_RIGHT_ANGLE = 0x6a,  // ┘
    DEC_UPPER_RIGHT_ANGLE = 0x6b,   // ┐
    DEC_UPPER_LEFT_ANGLE = 0x6c,    // ┌
    DEC_BOTTOM_LEFT_ANGLE = 0x6d,   // └
    DEC_CENTER_CROSS_LINE = 0x6e,   // ┼
    DEC_HORIZONTAL_LINE = 0x71,     // ─
    DEC_LEFT_TEE_LINE = 0x74,       // ├
    DEC_RIGHT_TEE_LINE = 0x75,      // ┤
    DEC_BOTTOM_TEE_LINE = 0x76,     // ┴
    DEC_UPPER_TEE_LINE = 0x77,      // ┬
    DEC_VERTICAL_LINE = 0x78        // │
};

/* ALTERNATE SCREEN BUFFER */

enum SCREEN_BUFFER {
    ALTERNATE_SCREEN_BUFFER = 104,
    MAIN_SCREEN_BUFFER = 108
};

#endif /* _TERMINAL_CONSTANTS_INCLUDED_H_ */
